{{- if .Values.otlp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-llmd.fullname" . }}-otlp
  namespace: {{ .Release.Namespace }}
  labels: {{- include "vllm-llmd.labels" . | nindent 4 }}
type: Opaque
stringData:
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otlp.endpoint | quote }}
  OTEL_EXPORTER_OTLP_HEADERS: {{ .Values.otlp.headers | quote }}
{{- end }}
